// NOTE: Assertions have been autogenerated by hlo/tools/generate_hlo_test_checks.py
// RUN: hlo-opt --passes=test-only-xla-builder --split-input-file %s | FileCheck %s

// CHECK-LABEL: HloModule cosh_f32, entry_computation_layout={(f32[])->f32[]}

// CHECK:       %[[$xla_builder_math_Cosh_12:[^ ]+]]
// CHECK-NEXT:  %[[arg0_1:[^ ]+]] = f32[] parameter(0)
// CHECK-NEXT:  %[[constant_2:[^ ]+]] = f32[] constant(0.5)
// CHECK-NEXT:  %[[log_3:[^ ]+]] = f32[] log(%[[constant_2]])
// CHECK-NEXT:  %[[add_4:[^ ]+]] = f32[] add(%[[arg0_1]], %[[log_3]])
// CHECK-NEXT:  %[[exponential_5:[^ ]+]] = f32[] exponential(%[[add_4]])
// CHECK-NEXT:  %[[negate_6:[^ ]+]] = f32[] negate(%[[arg0_1]])
// CHECK-NEXT:  %[[add_7:[^ ]+]] = f32[] add(%[[negate_6]], %[[log_3]])
// CHECK-NEXT:  %[[exponential_8:[^ ]+]] = f32[] exponential(%[[add_7]])
// CHECK-NEXT:  %[[add_9:[^ ]+]] = f32[] add(%[[exponential_5]], %[[exponential_8]])
// CHECK-NEXT:  %[[constant_10:[^ ]+]] = f32[] constant(1)
// CHECK-NEXT:  ROOT %[[maximum_11:[^ ]+]] = f32[] maximum(%[[add_9]], %[[constant_10]])

// CHECK:       ENTRY %[[$main_3:[^ ]+]]
// CHECK-NEXT:  %[[Arg_0_1:[^ ]+]] = f32[] parameter(0)
// CHECK-NEXT:  %[[custom_call_2:[^ ]+]] = f32[] custom-call(%[[Arg_0_1]]), custom_call_target="xla_builder.math.Cosh"
// CHECK-NEXT:  ROOT %[[custom_call:[^ ]+]] = f32[] custom-call(%[[Arg_0_1]]), custom_call_target="xla_builder.math.Cosh", called_computations={%[[$xla_builder_math_Cosh_12]]}

HloModule cosh_f32, entry_computation_layout={(f32[])->f32[]}

ENTRY %main.3 (Arg_0.1: f32[]) -> f32[] {
  %Arg_0.1 = f32[] parameter(0)
  ROOT %custom-call.2 = f32[] custom-call(%Arg_0.1), custom_call_target="xla_builder.math.Cosh"
}

// -----

// CHECK-LABEL: HloModule cosh_f64, entry_computation_layout={(f64[])->f64[]}

// CHECK:       %[[$xla_builder_math_Cosh_12:[^ ]+]]
// CHECK-NEXT:  %[[arg0_1:[^ ]+]] = f64[] parameter(0)
// CHECK-NEXT:  %[[constant_2:[^ ]+]] = f64[] constant(0.5)
// CHECK-NEXT:  %[[log_3:[^ ]+]] = f64[] log(%[[constant_2]])
// CHECK-NEXT:  %[[add_4:[^ ]+]] = f64[] add(%[[arg0_1]], %[[log_3]])
// CHECK-NEXT:  %[[exponential_5:[^ ]+]] = f64[] exponential(%[[add_4]])
// CHECK-NEXT:  %[[negate_6:[^ ]+]] = f64[] negate(%[[arg0_1]])
// CHECK-NEXT:  %[[add_7:[^ ]+]] = f64[] add(%[[negate_6]], %[[log_3]])
// CHECK-NEXT:  %[[exponential_8:[^ ]+]] = f64[] exponential(%[[add_7]])
// CHECK-NEXT:  %[[add_9:[^ ]+]] = f64[] add(%[[exponential_5]], %[[exponential_8]])
// CHECK-NEXT:  %[[constant_10:[^ ]+]] = f64[] constant(1)
// CHECK-NEXT:  ROOT %[[maximum_11:[^ ]+]] = f64[] maximum(%[[add_9]], %[[constant_10]])

// CHECK:       ENTRY %[[$main_3:[^ ]+]]
// CHECK-NEXT:  %[[Arg_0_1:[^ ]+]] = f64[] parameter(0)
// CHECK-NEXT:  %[[custom_call_2:[^ ]+]] = f64[] custom-call(%[[Arg_0_1]]), custom_call_target="xla_builder.math.Cosh"
// CHECK-NEXT:  ROOT %[[custom_call:[^ ]+]] = f64[] custom-call(%[[Arg_0_1]]), custom_call_target="xla_builder.math.Cosh", called_computations={%[[$xla_builder_math_Cosh_12]]}

HloModule cosh_f64, entry_computation_layout={(f64[])->f64[]}

ENTRY %main.3 (Arg_0.1: f64[]) -> f64[] {
  %Arg_0.1 = f64[] parameter(0)
  ROOT %custom-call.2 = f64[] custom-call(%Arg_0.1), custom_call_target="xla_builder.math.Cosh"
}

// -----

// CHECK-LABEL: HloModule cosh_complex64, entry_computation_layout={(c64[])->c64[]}

// CHECK:       %[[$xla_builder_math_Cosh_10:[^ ]+]]
// CHECK-NEXT:  %[[arg0_1:[^ ]+]] = c64[] parameter(0)
// CHECK-NEXT:  %[[constant_2:[^ ]+]] = c64[] constant((0.5, 0))
// CHECK-NEXT:  %[[log_3:[^ ]+]] = c64[] log(%[[constant_2]])
// CHECK-NEXT:  %[[add_4:[^ ]+]] = c64[] add(%[[arg0_1]], %[[log_3]])
// CHECK-NEXT:  %[[exponential_5:[^ ]+]] = c64[] exponential(%[[add_4]])
// CHECK-NEXT:  %[[negate_6:[^ ]+]] = c64[] negate(%[[arg0_1]])
// CHECK-NEXT:  %[[add_7:[^ ]+]] = c64[] add(%[[negate_6]], %[[log_3]])
// CHECK-NEXT:  %[[exponential_8:[^ ]+]] = c64[] exponential(%[[add_7]])
// CHECK-NEXT:  ROOT %[[add_9:[^ ]+]] = c64[] add(%[[exponential_5]], %[[exponential_8]])

// CHECK:       ENTRY %[[$main_3:[^ ]+]]
// CHECK-NEXT:  %[[Arg_0_1:[^ ]+]] = c64[] parameter(0)
// CHECK-NEXT:  %[[custom_call_2:[^ ]+]] = c64[] custom-call(%[[Arg_0_1]]), custom_call_target="xla_builder.math.Cosh"
// CHECK-NEXT:  ROOT %[[custom_call:[^ ]+]] = c64[] custom-call(%[[Arg_0_1]]), custom_call_target="xla_builder.math.Cosh", called_computations={%[[$xla_builder_math_Cosh_10]]}

HloModule cosh_complex64, entry_computation_layout={(c64[])->c64[]}

ENTRY %main.3 (Arg_0.1: c64[]) -> c64[] {
  %Arg_0.1 = c64[] parameter(0)
  ROOT %custom-call.2 = c64[] custom-call(%Arg_0.1), custom_call_target="xla_builder.math.Cosh"
}

// -----

// CHECK-LABEL: HloModule cosh_complex128, entry_computation_layout={(c128[])->c128[]}

// CHECK:       %[[$xla_builder_math_Cosh_10:[^ ]+]]
// CHECK-NEXT:  %[[arg0_1:[^ ]+]] = c128[] parameter(0)
// CHECK-NEXT:  %[[constant_2:[^ ]+]] = c128[] constant((0.5, 0))
// CHECK-NEXT:  %[[log_3:[^ ]+]] = c128[] log(%[[constant_2]])
// CHECK-NEXT:  %[[add_4:[^ ]+]] = c128[] add(%[[arg0_1]], %[[log_3]])
// CHECK-NEXT:  %[[exponential_5:[^ ]+]] = c128[] exponential(%[[add_4]])
// CHECK-NEXT:  %[[negate_6:[^ ]+]] = c128[] negate(%[[arg0_1]])
// CHECK-NEXT:  %[[add_7:[^ ]+]] = c128[] add(%[[negate_6]], %[[log_3]])
// CHECK-NEXT:  %[[exponential_8:[^ ]+]] = c128[] exponential(%[[add_7]])
// CHECK-NEXT:  ROOT %[[add_9:[^ ]+]] = c128[] add(%[[exponential_5]], %[[exponential_8]])

// CHECK:       ENTRY %[[$main_3:[^ ]+]]
// CHECK-NEXT:  %[[Arg_0_1:[^ ]+]] = c128[] parameter(0)
// CHECK-NEXT:  %[[custom_call_2:[^ ]+]] = c128[] custom-call(%[[Arg_0_1]]), custom_call_target="xla_builder.math.Cosh"
// CHECK-NEXT:  ROOT %[[custom_call:[^ ]+]] = c128[] custom-call(%[[Arg_0_1]]), custom_call_target="xla_builder.math.Cosh", called_computations={%[[$xla_builder_math_Cosh_10]]}

HloModule cosh_complex128, entry_computation_layout={(c128[])->c128[]}

ENTRY %main.3 (Arg_0.1: c128[]) -> c128[] {
  %Arg_0.1 = c128[] parameter(0)
  ROOT %custom-call.2 = c128[] custom-call(%Arg_0.1), custom_call_target="xla_builder.math.Cosh"
}
