// NOTE: Assertions have been autogenerated by hlo/tools/generate_hlo_test_checks.py
// RUN: hlo-opt --passes=test-only-xla-builder --split-input-file %s | FileCheck %s

// CHECK-LABEL: HloModule main, entry_computation_layout={(f32[2,2]{1,0})->f32[2,2]{1,0}}

// CHECK:       %[[$xla_builder_matrix_GetMatrixDiagonalViaGather_9:[^ ]+]]
// CHECK-NEXT:  %[[arg0_1:[^ ]+]] = f32[2,2]{1,0} parameter(0)
// CHECK-NEXT:  %[[iota_2:[^ ]+]] = s32[2]{0} iota(), iota_dimension=0
// CHECK-NEXT:  %[[broadcast_3:[^ ]+]] = s32[2,2]{1,0} broadcast(%[[iota_2]]), dimensions={0}
// CHECK-NEXT:  %[[constant_4:[^ ]+]] = s32[] constant(0)
// CHECK-NEXT:  %[[broadcast_5:[^ ]+]] = s32[2]{0} broadcast(%[[constant_4]]), dimensions={}
// CHECK-NEXT:  %[[broadcast_6:[^ ]+]] = s32[2,2]{1,0} broadcast(%[[broadcast_5]]), dimensions={1}
// CHECK-NEXT:  %[[add_7:[^ ]+]] = s32[2,2]{1,0} add(%[[broadcast_3]], %[[broadcast_6]])
// CHECK-NEXT:  ROOT %[[gather_8:[^ ]+]] = f32[2]{0} gather(%[[arg0_1]], %[[add_7]]), offset_dims={}, collapsed_slice_dims={0,1}, start_index_map={0,1}, index_vector_dim=1, slice_sizes={1,1}, indices_are_sorted=true

// CHECK:       ENTRY %[[$main_3:[^ ]+]]
// CHECK-NEXT:  %[[Arg_0_1:[^ ]+]] = f32[2,2]{1,0} parameter(0)
// CHECK-NEXT:  %[[custom_call_2:[^ ]+]] = f32[2,2]{1,0} custom-call(%[[Arg_0_1]]), custom_call_target="xla_builder.matrix.GetMatrixDiagonalViaGather"
// CHECK-NEXT:  ROOT %[[custom_call:[^ ]+]] = f32[2,2]{1,0} custom-call(%[[Arg_0_1]]), custom_call_target="xla_builder.matrix.GetMatrixDiagonalViaGather", called_computations={%[[$xla_builder_matrix_GetMatrixDiagonalViaGather_9]]}

HloModule main, entry_computation_layout={(f32[2,2])->f32[2,2]}

ENTRY %main.3 (Arg_0.1: f32[2,2]) -> f32[2,2] {
  %Arg_0.1 = f32[2,2] parameter(0)
  ROOT %custom-call.2 = f32[2,2] custom-call(%Arg_0.1), custom_call_target="xla_builder.matrix.GetMatrixDiagonalViaGather"
}